services:
  - type: web
    name: qr-shop-catalog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 4 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: TURSO_DATABASE_URL
        value: libsql://shop-yashyash.aws-ap-south-1.turso.io
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: mhtvnxwl
      - key: CLOUDINARY_API_KEY
        value: 971758454512911
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
